version: '3'

services:
  mysql:
    image: mysql:5.6.35
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
      - MYSQL_DATABASE=develop
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./xxtra/mysql:/var/lib/mysql
