version: '3'

services:
  mysql:
    image: mysql:5.6.35
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
      - MYSQL_DATABASE=develop
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./xxtra/mysql:/var/lib/mysql
  redis:
    image: redis
    ports:
      - "6379:6379"
  application:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=dev
      - MYSQL_PASS=dev
      - MYSQL_DB=develop
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mysql
      - redis
